package com.example.sessionmanagement;

import javax.servlet.*;
import javax.servlet.http.*;
import java.io.IOException;
import java.io.PrintWriter;
/**
 * This servlet will handle the login information the client will enter
 * inside the login.html page.
*/

public class LoginServlet extends HttpServlet {
    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {

    }
/**
 * This method will take the username and password values the user
 * enters in the login page and matches it to "anas" and "jawad"
 * respectively.
 * If the credentials are correct, then the
 * username will be saved in a cookie to maintain the state information
 * of the user, the cookie object will be added to the Httpresponse
 * object, and the user will be redirected to the page generated by
 * LoginSuccessfulServlet. The reason we are not redirecting the user to
 * a static loginSuccessful.html page is because a static resource does
 * not have any way of its own to verify that the user is logged in, for
 * which we use a servlet (LoginSuccessfulServlet) to at first
 * authenticate the user and then show the corresponding LoginSuccessful
 * page.
 * If the credentials are incorrect, then we send the user back to the
 * login page.
 * @param request the request object that carries the client information
 * @param response the response object that will be sent to the client
**/
    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        String username = request.getParameter("username-field");
        String password = request.getParameter("pw-field");

        if (username.equals("anas") && password.equals("jawad"))
        {
            Cookie usernameCookie = new Cookie("usernameKey", username);
            response.addCookie(usernameCookie);

            PrintWriter out = response.getWriter();
            out.println("<h1> Successfully logged in </h1>");

            RequestDispatcher rd = request.getRequestDispatcher(
                    "loginsuccessful");
            rd.include(request, response);
        }
        else
        {
            PrintWriter out = response.getWriter();
            out.println("<h1> Wrong credentials </h1>");

            RequestDispatcher rd = request.getRequestDispatcher(
                    "login.html");
            rd.include(request, response);
        }
    }
}
